enum StatusRequest {
  none,
  loading,
  success,
  failure,
  serverfailure,
  serverException,
  offlinefailure,
  emptyAddress,
  emptyOrders,
  emptyNotification,
  emptyFavorite,
  delivaryMustCompleteOrders,
  delivaryEmptyOrders,
}
