// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd9mfs2ZZf0KagTArIkScfFQy2Mxkut5Q',
    appId: '1:330353146783:web:bd86dc4e99fb8500229baa',
    messagingSenderId: '330353146783',
    projectId: 'express-corner',
    authDomain: 'express-corner.firebaseapp.com',
    storageBucket: 'express-corner.appspot.com',
    measurementId: 'G-XB9YDWR33C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvdABkGNpafpQzeF647TR4XM0qjgLOJqQ',
    appId: '1:330353146783:android:9f693bc04a24793b229baa',
    messagingSenderId: '330353146783',
    projectId: 'express-corner',
    storageBucket: 'express-corner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnMu_bo9mcusQCSlqYfrR921PHn1moVzI',
    appId: '1:330353146783:ios:605c51f4263fd3e4229baa',
    messagingSenderId: '330353146783',
    projectId: 'express-corner',
    storageBucket: 'express-corner.appspot.com',
    iosBundleId: 'com.example.expressCorner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnMu_bo9mcusQCSlqYfrR921PHn1moVzI',
    appId: '1:330353146783:ios:6b2dbd3cfff2a358229baa',
    messagingSenderId: '330353146783',
    projectId: 'express-corner',
    storageBucket: 'express-corner.appspot.com',
    iosBundleId: 'com.example.expressCorner.RunnerTests',
  );
}
